name: Deploy Indestructible

on:
  push:
    branches: [ "feature/dockerizacion" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Despliegue en Servidor appsur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/pipeline/pipeline
            git pull origin feature/dockerizacion
            
            # Construcción ultra rápida
            docker build -t mi-web-app:latest .
            
            # Reemplazo atómico
            docker rm -f web-produccion || true
            
            docker run -d \
              --name web-produccion \
              --restart always \
              -p 12345:8000 \
              mi-web-app:latest
            
            # Limpieza de imágenes viejas
            docker image prune -f
