name: Deploy Local Directo

on:
  push:
    branches: [ "feature/dockerizacion", "main" ]

jobs:
  deploy:
    # Usamos 'self-hosted' porque tú ya tienes un runner en tu servidor
    runs-on: self-hosted 

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Build y Run Manual
        run: |
          cd ~/pipeline/pipeline
          git pull origin feature/dockerizacion || git pull origin main
          
          # Construir usando el caché que ya configuramos
          docker build -t mi-web-app:latest .
          
          # Parar el viejo y lanzar el nuevo
          docker rm -f web-produccion || true
          
          docker run -d \
            --name web-produccion \
            --restart always \
            -p 12345:8000 \
            mi-web-app:latest
          
          # Limpiar imágenes huérfanas
          docker image prune -f
